import { DeliberationSession, ConsensusResult } from '../types';

const STORAGE_KEY_HISTORIES = 'MAGI_DELIBERATION_HISTORIES_V1';
const MAX_HISTORIES = 30;

export function loadSessions(): DeliberationSession[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY_HISTORIES);
    if (!raw) return [];
    return JSON.parse(raw) as DeliberationSession[];
  } catch (err) {
    console.error('Failed to load deliberation histories:', err);
    return [];
  }
}

export function saveSession(session: DeliberationSession): DeliberationSession[] {
  try {
    const existing = loadSessions();
    const filtered = existing.filter(s => s.id !== session.id);
    const updated = [session, ...filtered].slice(0, MAX_HISTORIES);
    localStorage.setItem(STORAGE_KEY_HISTORIES, JSON.stringify(updated));
    return updated;
  } catch (err) {
    console.error('Failed to save deliberation session:', err);
    return loadSessions();
  }
}

export function deleteSession(id: string): DeliberationSession[] {
  try {
    const existing = loadSessions();
    const updated = existing.filter(s => s.id !== id);
    localStorage.setItem(STORAGE_KEY_HISTORIES, JSON.stringify(updated));
    return updated;
  } catch (err) {
    console.error('Failed to delete session:', err);
    return loadSessions();
  }
}

export function clearSessions(): void {
  try {
    localStorage.removeItem(STORAGE_KEY_HISTORIES);
  } catch (err) {
    console.error('Failed to clear sessions:', err);
  }
}

export function getSessionById(id: string): DeliberationSession | undefined {
  const sessions = loadSessions();
  return sessions.find(s => s.id === id);
}

/**
 * 過去の合議結果から、プロンプト注入用のコンパクトなテキストサマリーを生成
 */
export function formatConsensusSummary(session: DeliberationSession): string {
  const c = session.consensus;
  const decisionText = c.finalStanceLabel || c.finalDecision;
  
  return `【直前の合議結果 (SESSION_ID: ${session.id})】
- 前回の検討議題: ${session.query}
- 最終決議: ${decisionText}
- 統括エグゼクティブサマリー: ${c.executiveSummary}
- 推奨アクション: ${c.actionableRecommendation}
${c.keyDisagreements && c.keyDisagreements.length > 0 ? `- 主な対立点・懸念: ${c.keyDisagreements.join(' / ')}` : ''}`;
}

/**
 * 合議セッション全体を美しいマークダウンレポート文字列として出力
 */
export function exportSessionToMarkdown(session: DeliberationSession): string {
  const c = session.consensus;
  const decisionLabel = c.finalStanceLabel || c.finalDecision;
  const votes = c.voteCounts ? `[可決: ${c.voteCounts.APPROVAL} / 否決: ${c.voteCounts.DENIED} / 条件付: ${c.voteCounts.CONDITIONAL}]` : '';

  let md = `# MAGI SYSTEM CONSENSUS REPORT (CODE: 601)

- **SESSION ID**: \`${session.id}\`
- **日時**: ${session.timestamp}
- **プロトコルモード**: ${session.mode}
${session.parentSessionId ? `- **継続審議親セッション**: \`${session.parentSessionId}\`\n` : ''}
---

## 検討議題 (AGENDA)
> ${session.query}

${session.attachedDoc ? `### 【参照外部ドキュメント】\n- **タイトル**: ${session.attachedDoc.title}\n- **URL**: ${session.attachedDoc.url}\n` : ''}
---

## 最終決議 (JUDGMENT)
### **【 ${decisionLabel} 】** ${votes}

### 統括エグゼクティブサマリー (EXECUTIVE SUMMARY)
${c.executiveSummary}

### 熟議統合詳細 (SYNTHESIS)
${c.synthesisDetails}

${c.keyDisagreements && c.keyDisagreements.length > 0 ? `### 主な論点・対立懸念 (KEY DISAGREEMENTS)\n${c.keyDisagreements.map(d => `- ${d}`).join('\n')}\n` : ''}
### 推進行動指針 (ACTIONABLE RECOMMENDATION)
${c.actionableRecommendation}

---

## MAGI 3基の個別主張および熟議経過 (INDIVIDUAL PERSPECTIVES)

`;

  const magiNames: Record<string, string> = {
    MELCHIOR: 'MELCHIOR-1 (思考理念: 科学・技術論理)',
    BALTHASAR: 'BALTHASAR-2 (思考理念: 律法・倫理・人間愛)',
    CASPAR: 'CASPAR-3 (思考理念: 直感・保身・現実解)'
  };

  (['MELCHIOR', 'BALTHASAR', 'CASPAR'] as const).forEach((id) => {
    const init = session.initialOutputs?.[id];
    const delib = session.deliberationOutputs?.[id];
    if (!init) return;

    md += `### ■ ${magiNames[id]}\n`;
    md += `- **初案主張**: ${init.stanceLabel || init.initialVote} (${init.initialVote})\n`;
    md += `- **初案根拠**: ${init.reasoning}\n`;
    if (init.conditions) {
      md += `- **提示前提条件**: ${init.conditions}\n`;
    }
    if (delib) {
      md += `- **熟議後修正主張**: ${delib.revisedStanceLabel || delib.revisedVote} (${delib.revisedVote})\n`;
      md += `- **熟議論点・コメント**: ${delib.refinements}\n`;
      md += `- **最終主張根拠**: ${delib.finalArgument}\n`;
    }
    md += `\n`;
  });

  md += `\n---\n*Report generated by NERV MAGI SUPERCOMPUTER SYSTEM 01*\n`;

  return md;
}

/**
 * テキストコンテンツをマークダウンファイルとしてダウンロード発火
 */
export function downloadMarkdownFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

